CREATE TABLE IF NOT EXISTS `audit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `link` varchar(1000) NOT NULL,
  `user_id` int(11) NOT NULL,
  `ip` varchar(64) NOT NULL,
  `post` text NOT NULL,
  `get` text NOT NULL,
  `files` text NOT NULL,
  `session` text NOT NULL,
  `server` text NOT NULL,
  `cookie` text NOT NULL,
  `referrer` varchar(1000) NOT NULL,
  `redirect` varchar(1000) NOT NULL,
  `app_version` varchar(255) NOT NULL,
  `yii_version` varchar(255) NOT NULL,
  `audit_trail_count` int(11) NOT NULL,
  `start_time` decimal(14,4) NOT NULL,
  `end_time` decimal(14,4) NOT NULL,
  `total_time` decimal(14,4) NOT NULL,
  `memory_usage` int(11) NOT NULL,
  `memory_peak` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `preserve` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `stamp` (`created`),
  KEY `user_id` (`user_id`),
  KEY `url` (`link`(255)),
  KEY `audit_trail_count` (`audit_trail_count`),
  KEY `redirect` (`redirect`(255)),
  KEY `app_version` (`app_version`),
  KEY `start_time` (`start_time`),
  KEY `end_time` (`end_time`),
  KEY `total_time` (`total_time`),
  KEY `memory_usage` (`memory_usage`),
  KEY `memory_peak` (`memory_peak`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS `audit_trail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `audit_id` int(11) NOT NULL,
  `old_value` text NOT NULL,
  `new_value` text NOT NULL,
  `action` varchar(20) NOT NULL,
  `model` varchar(255) NOT NULL,
  `model_id` varchar(64) NOT NULL,
  `field` varchar(64) NOT NULL,
  `created` datetime DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `model_id` (`model_id`),
  KEY `model` (`model`),
  KEY `field` (`field`),
  KEY `action` (`action`),
  KEY `page_trail_id` (`audit_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;
