<?php
/**
 * --- BEGIN AutoGenerated by tool/generateProperties ---
 *
 * This is the model class for table 'sort_order'
 *
 * @method SortOrder with() with()
 * @method SortOrder find() find($condition, array $params = array())
 * @method SortOrder[] findAll() findAll($condition = '', array $params = array())
 * @method SortOrder findByPk() findByPk($pk, $condition = '', array $params = array())
 * @method SortOrder[] findAllByPk() findAllByPk($pk, $condition = '', array $params = array())
 * @method SortOrder findByAttributes() findByAttributes(array $attributes, $condition = '', array $params = array())
 * @method SortOrder[] findAllByAttributes() findAllByAttributes(array $attributes, $condition = '', array $params = array())
 * @method SortOrder findBySql() findBySql($sql, array $params = array())
 * @method SortOrder[] findAllBySql() findAllBySql($sql, array $params = array())
 *
 * Properties from table fields
 * @property integer $id
 * @property string $model
 * @property integer $model_id
 * @property integer $sort_order
 *
 * --- END AutoGenerated by tool/generateProperties ---
 *
 * @package app.model
 * @author Brett O'Donnell <brett@mrphp.com.au>
 */
class YdSortOrder extends YdActiveRecord
{

    /**
     * Returns the static model of the specified AR class.
     * @param string $className
     * @return SortOrder the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'sort_order';
    }

}
